language: node_js
node_js: "8.10"

before_script:
    - npm install

script:
    - node ./deploy/tests/lint.js

before_deploy:
    - apt-get install python-pip
    - pip install awscli
    - export PATH=$PATH:$HOME/.local/bin

deploy:
    provider: script
    script: ./deploy/build.sh
    on:
        branch: master
